### ISSUE TITLE
Modifying the name of exporters

### ISSUE THREAD

**Issue by julez2310** [Palleri/DCW#11]
Hi.
Is there a way to modify the names of exporters? The name of the container seems to do nothing.
<img width="369" alt="Bildschirmfoto 2023-12-02 um 13 10 28" src="https://github.com/Palleri/DCW/assets/88155961/3fd40889-2307-4b87-aed4-d9a69661b0a1">

Thanks.

**Comment by Palleri** [comment]
Hi, yes there is.
You can use the `hostname:` settings in your docker-compose.

```
version: '3.2'
services:
  dcw:
    hostname: dcw
```
