### ISSUE TITLE
Website Not Working with Reverse Proxy

### ISSUE THREAD

**Issue by Ashkaan** [Palleri/DCW#15]
I use Traefik v3, and when I go to the site, I see this, instead of the regular site:

<img width="314" alt="image" src="https://github.com/user-attachments/assets/e2ce5a38-f250-4d42-83e9-f5de52142e0a">

When I go via local hostname, it works great.

I have tried putting the reverse proxy address as an environment variable "HTTPS_PROXY", but that doesn't work (and I don't think that's what that environment variable is supposed to do.

Here's my docker compose:
```
name: dcw
services:
  dcw:
    container_name: dcw
    environment:
      CRON_TIME: 2:00
 #     HTTPS_PROXY: https://{obfiscated}:443
      TOKEN: ${Secret}
    image: palleri/dcw:latest
    hostname: TrueNAS
    network_mode: bridge
    ports:
      - 8060:80
      - 5432:5432
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
networks:
  bridge: {}
```
