### ISSUE TITLE
Collapse hosts in table

### ISSUE THREAD

**Issue by danmed** [Palleri/DCW#3]
Would it be possible to collapse the table below the host name on the "containers on latest version" side on the main index page?

Alternatively, could we have 1 list where all the hosts are collapsed except the ones that need updates and updates are highlighted or something?

I want this to be a one stop shop for me where i will visit it once a day etc and at the moment due to me having in excess of 15 hosts it's looking a bit unruly :)

![image](https://user-images.githubusercontent.com/3878490/224514526-d9f209e1-c60f-48cd-95c9-4406a71863bd.png)

If i can delve into my PHP past i'll see if i can do a PR but with you having designed it it might be quicker if you have the know how.

**Comment by Palleri** [comment]
Yep, I am thinking exactly the same. I have roughly as many as you and it dosnt really look that good with so many containers.
I am planning to fix this hopefully soon.

Also, use the HOSTNAME variable in docker-compose so that your hostname is presented on DCW page.

```
  dcw-exporter:
    container_name: dcw-exporter
    image: 'palleri/dcw-exporter:latest'
    hostname: host2-exporter
    restart: unless-stopped
```
