### ISSUE TITLE
Container id's displayed rather than container names

### ISSUE THREAD

**Issue by defeatedbythecat** [Palleri/DCW#7]
Not sure if I have something misconfigured or not. Would be great if you could in the docker compose add a custom name

**Comment by edersong** [comment]
Just configure `hostname: name`

**Comment by Palleri** [comment]
Yes, this is right.

```
version: '3.2'
services:
  int-dockcheck-web:
    container_name: int-dockcheck-web
    hostname: HOST-DOCKER
    image: 'palleri/dcw:latest'
    restart: always
```
